import Head from 'next/head'
import styles from '../styles/Home.module.css'
import BodyLeft from "../Components/BodyLeft"
import BodyMiddle from "../Components/BodyMiddle"
import BodyRight from "../Components/BodyRight"
import Header from '../Components/Header'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hexi | Roadmap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <Header/>
      <main className='grid lg:grid-cols-gbody'>
        <BodyLeft/>
        <BodyMiddle pfp="home_pfp.svg" title="The Hexi Roadmap" />
        <BodyRight/>
      </main>
    </div>
  )
}
